server:
  port: ${auth-service.port}

spring:
  datasource:
    url: ${AUTH_SERVICE_MYSQL_URL}
    username: ${AUTH_SERVICE_MYSQL_USERNAME}
    password: ${AUTH_SERVICE_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      
  redis:
    host: ${AUTH_SERVICE_REDIS_HOST}
    port: ${AUTH_SERVICE_REDIS_PORT:16379}
    password: ${AUTH_SERVICE_REDIS_PASSWORD:}
    database: ${AUTH_SERVICE_REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms


  application:
    name: auth-server

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.doooogh.farm.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.doooogh.farm.auth.controller

# 日志配置
logging:
  level:
    root: INFO
    com.doooogh.farm: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  serialization:
    write-dates-as-timestamps: false