spring:
  datasource:
    url: ${MYSQL_URL:@mysql.url.pattern@}
    username: ${MYSQL_USERNAME:@mysql.username@}
    password: ${MYSQL_PASSWORD:@mysql.password@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${MYSQL_MAX_POOL_SIZE:20}
      minimum-idle: ${MYSQL_MIN_IDLE:5}
    
  redis:
    host: ${REDIS_HOST:@redis.host@}
    port: ${REDIS_PORT:@redis.port@}
    password: ${REDIS_PASSWORD:@redis.password@}
    database: ${REDIS_DATABASE:@redis.database@}
    lettuce:
      pool:
        max-active: ${REDIS_MAX_ACTIVE:8}
        max-idle: ${REDIS_MAX_IDLE:8}
        min-idle: ${REDIS_MIN_IDLE:0}
    
  rabbitmq:
    host: ${RABBITMQ_HOST:@rabbitmq.host@}
    port: ${RABBITMQ_PORT:@rabbitmq.port@}
    username: ${RABBITMQ_USERNAME:@rabbitmq.username@}
    password: ${RABBITMQ_PASSWORD:@rabbitmq.password@}
    listener:
      simple:
        concurrency: ${RABBITMQ_CONCURRENCY:5}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY:10}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.doooogh.farm: ${LOG_LEVEL_APP:DEBUG}
  file:
    path: ${LOG_PATH:/var/log}
    name: ${spring.application.name}.log 