spring:
  datasource:
    url: jdbc:mysql://${db.system.host}:${db.system.port}/${db.system}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${db.system.username}
    password: ${db.system.password} 