spring:
  cloud:
    gateway:
      routes:
        - id: some-service
          uri: lb://some-service
          predicates:
            - Path=/some/path/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}" 