server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080
          jwk-set-uri: http://auth-service:8080/.well-known/jwks.json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${USER_SERVICE_MYSQL_URL}
    username: ${USER_SERVICE_MYSQL_USERNAME}
    password: ${USER_SERVICE_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

  redis:
    host: ${USER_SERVICE_REDIS_HOST}
    port: ${USER_SERVICE_REDIS_PORT:16379}
    password: ${USER_SERVICE_REDIS_PASSWORD:}
    database: ${USER_SERVICE_REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# 日志配置
logging:
  level:
    root: INFO
    com.doooogh.farm: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO