server:
  port: ${server.ports.user-service}

spring:
  profiles:
    active: ${spring.profiles.active:dev}
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  cloud:
    stream:
      bindings:
        userCreatedOutput:
          destination: user.created
          content-type: application/json
        userUpdatedOutput:
          destination: user.updated
          content-type: application/json
      rabbit:
        bindings:
          userCreatedOutput:
            producer:
              routing-key-expression: headers.eventType
          userUpdatedOutput:
            producer:
              routing-key-expression: headers.eventType
    nacos:
      discovery:
        enabled: true
      server-addr: ${nacos.host}:${nacos.port}
      namespace: ${nacos.namespace:}
      group: ${nacos.group:DEFAULT_GROUP}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
feign:
  auth-service:
    url: http://localhost:8081
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full 