server:
  port: 8081

spring:
  application:
    name: auth-service
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_db?useSSL=false&serverTimezone=UTC
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: # 如果有密码，请设置
    database: 0 