# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.doooogh.farm.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0 

jwt:
  secret: your-secret-key-your-secret-key-your-secret-key
  token-expiration: 24
  refresh-token-expiration: 7
  issuer: com.doooogh.farm 

cloud:
  nacos:
    discovery:
      enabled: true
    config:
      server-addr: ${nacos.host}:${nacos.port}
      namespace: ${nacos.namespace:}
      group: ${nacos.group:DEFAULT_GROUP}

nacos:
  server-addr: ${nacos.host}:${nacos.port}
  namespace: ${nacos.namespace:}
  group: ${nacos.group:DEFAULT_GROUP} 

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          custom:
            client-id: ${CUSTOM_CLIENT_ID:farm-client}
            client-secret: ${CUSTOM_CLIENT_SECRET:farm-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          custom:
            authorization-uri: ${CUSTOM_AUTH_URI:http://localhost:8081/oauth2/authorize}
            token-uri: ${CUSTOM_TOKEN_URI:http://localhost:8081/oauth2/token}
            user-info-uri: ${CUSTOM_USER_INFO_URI:http://localhost:8081/userinfo}
            jwk-set-uri: ${CUSTOM_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json} 