spring:
  datasource:
    url: jdbc:mysql://${db.auth.host}:${db.auth.port}/${db.auth}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${db.auth.username}
    password: ${db.auth.password} 