server:
  port: ${user-service.port}

spring:
  datasource:
    url: jdbc:mysql://${db.user.host}:${db.user.port}/${db.user}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${db.user.username}
    password: ${db.user.password}
    druid:
      # 只保留需要覆盖的配置
      initial-size: 5
      min-idle: 10
      max-active: 20

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full 