spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.user}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${db.username}
    password: ${db.password} 